# Generated by Django 3.1.3 on 2020-11-30 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LadoLente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='observacion',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('nombre', models.CharField(max_length=64)),
                ('detalle', models.CharField(max_length=150)),
                ('armazon', models.BooleanField()),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productoClasificacion', to='web_app.ladolente')),
                ('lado_lente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productoLenteLado', to='web_app.ladolente')),
                ('tipo_lente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productoLenteTipo', to='web_app.tipolente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField()),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidoEstado', to='web_app.estadopedido')),
                ('productos', models.ManyToManyField(blank=True, related_name='productosPedidos', to='web_app.Producto')),
                ('tipo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidoTipoPago', to='web_app.tipopago')),
            ],
        ),
    ]
