# Generated by Django 3.1.3 on 2020-11-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20201130_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopedido',
            name='descripcion',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.RunSQL(
            "INSERT INTO 'web_app_estadopedido' VALUES (1, 'Pendiente')"
        )
    ]
