# Generated by Django 3.1.3 on 2020-11-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_estadopedido_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='detalle',
            field=models.CharField(max_length=152),
        ),
        migrations.RunSQL('''
            INSERT INTO 'web_app_estadopedido' VALUES (2, 'Pedido');
            INSERT INTO 'web_app_estadopedido' VALUES (3, 'Taller');
            INSERT INTO 'web_app_estadopedido' VALUES (4, 'Finalizado');
            INSERT INTO 'web_app_tipopago' VALUES (1, 'Tarjeta Credito');
            INSERT INTO 'web_app_tipopago' VALUES (2, 'Tarjeta Debito');
            INSERT INTO 'web_app_tipopago' VALUES (3, 'Efectivo');
            INSERT INTO 'web_app_tipopago' VALUES (4, 'Billetera virtual');
            INSERT INTO 'web_app_tipolente' VALUES (1, 'Cerca');
            INSERT INTO 'web_app_tipolente' VALUES (2, 'Lejos');
            INSERT INTO 'web_app_ladolente' VALUES (1, 'Izquierda');
            INSERT INTO 'web_app_ladolente' VALUES (2, 'Derecha');
            INSERT INTO 'web_app_ladolente' VALUES (3, 'Ambos');
            INSERT INTO 'web_app_clasificacion' VALUES (1, 'Lente');
            INSERT INTO 'web_app_clasificacion' VALUES (2, 'Armazon');
            INSERT INTO 'web_app_clasificacion' VALUES (3, 'Estuche');'''
        )
    ]
